name: Migrate GitHub Teams

on:
  workflow_dispatch:
    inputs:
      source-org:
        description: 'Source GitHub organization name'
        required: true
        type: string
      target-org:
        description: 'Target GitHub organization name'
        required: true
        type: string
      mapping-csv-path:
        description: 'Path to user mapping CSV file'
        required: true
        default: 'user-map.csv'
        type: string

jobs:
  migrate-teams:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check GitHub CLI version
        run: gh --version

      - name: Run Team Migration PowerShell Script
        shell: pwsh
        run: |
          ./migration/Migrate-GitHubTeams.ps1 `
            -SourcePAT $env:SOURCE_PAT `
            -TargetPAT $env:TARGET_PAT `
            -SourceOrg "source-org-name" `
            -TargetOrg "target-org-name" `
            -UserMappingCsv "./user-map.csv"
