name: Migrate GitHub Teams

on:
  workflow_dispatch:
    inputs:
      source-org:
        description: 'Source GitHub organization name'
        required: true
        type: string
      target-org:
        description: 'Target GitHub organization name'
        required: true
        type: string
      mapping-csv-path:
        description: 'Path to user mapping CSV file'
        required: true
        default: 'user-map.csv'
        type: string

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run Migration Script
        env:
          GH_TOKEN: ${{ secrets.TARGET_PAT }}
          SOURCE_PAT: ${{ secrets.SOURCE_PAT }}
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          pwsh -NoLogo -NoProfile -ExecutionPolicy Bypass -File migration/Migrate-GitHubTeams.ps1 \
            -SourceOrg "${{ github.event.inputs.source_org }}" \
            -TargetOrg "${{ github.event.inputs.target_org }}" \
            -UserMappingCsv "./user-map.csv" \
            -SourcePAT "${{ secrets.SOURCE_PAT }}" \
            -TargetPAT "${{ secrets.TARGET_PAT }}"  \
