name: "Migrate GitHub Teams"

on:
  workflow_dispatch:
    inputs:
      source_org:
        description: 'Source organization name'
        required: true
      target_org:
        description: 'Target organization name'
        required: true
      user_mapping_csv:
        description: 'Path to the CSV file with user mapping'
        required: true
      dry_run:
        description: 'Enable dry-run mode (true/false)'
        required: false
        default: 'false'

jobs:
  migrate-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install PowerShell
        run: |
          sudo apt-get install -y powershell

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Run Team Migration Script
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          pwsh -NoLogo -NoProfile -ExecutionPolicy Bypass -File migration/Migrate-GitHubTeams.ps1 \
            -SourceOrg "${{ github.event.inputs.source_org }}" \
            -TargetOrg "${{ github.event.inputs.target_org }}" \
            -UserMappingCsv "${{ github.event.inputs.user_mapping_csv }}" \
            $([ "${{ github.event.inputs.dry_run }}" == 'true' ] && echo "-DryRun")
